package cashregister::Model::cashregister;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'cashregister::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=cash;host=localhost;',
        user => 'cash',
        password => 'cash',
        AutoCommit => q{1},
    }
);

=head1 NAME

cashregister::Model::cashregister - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<cashregister>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<cashregister::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.61

=head1 AUTHOR

amit

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
